language:
  - ruby
rvm:
  - 2.2.6
  - 2.3.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "cd spec/dummy && bundle exec rake db:create db:migrate && cd -"
